### ISSUE TITLE
Error logs

### ISSUE THREAD

**Issue by ne0ark** [l3uddz/sonarrAnnounced#12]
```
Mar 26 07:26:40 test mono[2027]: [Info] DownloadDecisionMaker: Processing 1 releases
Mar 26 07:26:40 test python3[782]: DEBUG:IPTORRENTS:Sonarr rejected release: Married At First Sight AU S04E25 HDTV x264-FQM
Mar 26 07:29:39 test python3[782]: ERROR:UTILS:Exception while get_id:
Mar 26 07:29:39 test python3[782]: Traceback (most recent call last):
Mar 26 07:29:39 test python3[782]:   File "/home/test/sonarrAnnounced/utils.py", line 27, in get_id
Mar 26 07:29:39 test python3[782]:     torrent_id = m[group]
Mar 26 07:29:39 test python3[782]: IndexError: list index out of range
Mar 26 07:29:55 test mono[2027]: [Info] RssSyncService: Starting RSS Sync
Mar 26 07:29:58 test mono[2027]: [Info] DownloadDecisionMaker: Processing 304 releases
Mar 26 07:29:58 test mono[2027]: [Info] RssSyncService: RSS Sync Completed. Reports found: 304, Reports grabbed: 0
Mar 26 07:37:00 test python3[782]: ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fd830315d08>, <pydle.features.rfc1459.parsing.RFC1459Message object at 0x7fd83026bb38>)
Mar 26 07:37:00 test python3[782]: Traceback (most recent call last):
Mar 26 07:37:00 test python3[782]:   File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 604, in _run_callback
Mar 26 07:37:00 test python3[782]:     ret = callback()
Mar 26 07:37:00 test python3[782]:   File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
Mar 26 07:37:00 test python3[782]:     return fn(*args, **kwargs)
Mar 26 07:37:00 test python3[782]:   File "/usr/local/lib/python3.5/dist-packages/pydle/features/rfc1459/client.py", line 623, in on_raw_mode
Mar 26 07:37:00 test python3[782]:     self.channels[target]['modes'] = self._parse_channel_modes(target, modes)
Mar 26 07:37:00 test python3[782]:   File "/usr/local/lib/python3.5/dist-packages/pydle/features/rfc1459/client.py", line 131, in _parse_channel_modes
Mar 26 07:37:00 test python3[782]:     return parsing.parse_modes(modes, current, behaviour=self._channel_modes_behaviour)
Mar 26 07:37:00 test python3[782]:   File "/usr/local/lib/python3.5/dist-packages/pydle/features/rfc1459/parsing.py", line 239, in parse_modes
Mar 26 07:37:00 test python3[782]:     mode=mode, s='+' if add else '-'), ' '.join(modes))
Mar 26 07:37:00 test python3[782]: pydle.protocol.ProtocolViolation: Attempted to parse mode with parameter (+v) but no parameters left in mode list.
```

```
Mar 26 03:26:23 test python3[782]: ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fd8302912f0>, <pydle.features.rfc1459.parsing.RFC1459Message object at 0x7fd8302e1438>)
Mar 26 03:26:23 test python3[782]: Traceback (most recent call last):
Mar 26 03:26:23 test python3[782]:   File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 604, in _run_callback
Mar 26 03:26:23 test python3[782]:     ret = callback()
Mar 26 03:26:23 test python3[782]:   File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
Mar 26 03:26:23 test python3[782]:     return fn(*args, **kwargs)
Mar 26 03:26:23 test python3[782]:   File "/usr/local/lib/python3.5/dist-packages/pydle/features/rfc1459/client.py", line 623, in on_raw_mode
Mar 26 03:26:23 test python3[782]:     self.channels[target]['modes'] = self._parse_channel_modes(target, modes)
Mar 26 03:26:23 test python3[782]:   File "/usr/local/lib/python3.5/dist-packages/pydle/features/rfc1459/client.py", line 131, in _parse_channel_modes
Mar 26 03:26:23 test python3[782]:     return parsing.parse_modes(modes, current, behaviour=self._channel_modes_behaviour)
Mar 26 03:26:23 test python3[782]:   File "/usr/local/lib/python3.5/dist-packages/pydle/features/rfc1459/parsing.py", line 239, in parse_modes
Mar 26 03:26:23 test python3[782]:     mode=mode, s='+' if add else '-'), ' '.join(modes))
Mar 26 03:26:23 test python3[782]: pydle.protocol.ProtocolViolation: Attempted to parse mode with parameter (+k) but no parameters left in mode list.
```

**Comment by l3uddz** [comment]
First one seems to be a failed attempt to retrieve the torrent id from announce message. The other one seems to be another pydle issue. At this point im thinking I'll probably just get rid of pydle and look at alternatives or write one.

**Comment by ne0ark** [comment]
No sure if this is sonarr or announced: https://github.com/Sonarr/Sonarr/issues/1799
