### ISSUE TITLE
On windows it brakes after the update of the 23th

### ISSUE THREAD

**Issue by TRaSH-** [l3uddz/sonarrAnnounced#7]
I'm using it on windows,
Didn't update for a while so thought it would be time.
I'm getting the following error when using the latest version.
c:\Python36\sonarrAnnounce.exe = renamen python3.exe so i know whats running when looking in tak manager.

`c:\sonarrAnnounced>c:\Python36\sonarrAnnounce.exe c:\sonarrAnnounced\bot.py
Traceback (most recent call last):
  File "c:\Python36\lib\site-packages\pony\orm\dbapiprovider.py", line 48, in wrap_dbapi_exceptions
    try: return func(provider, *args, **kwargs)
  File "c:\Python36\lib\site-packages\pony\orm\dbapiprovider.py", line 239, in execute
    if arguments is None: cursor.execute(sql)
sqlite3.OperationalError: no such column: Announced.torrent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\sonarrAnnounced\bot.py", line 5, in <module>
    import manager
  File "c:\sonarrAnnounced\manager.py", line 7, in <module>
    import webui
  File "c:\sonarrAnnounced\webui.py", line 13, in <module>
    import db
  File "c:\sonarrAnnounced\db.py", line 26, in <module>
    db.generate_mapping(create_tables=True)
  File "<string>", line 2, in generate_mapping
  File "c:\Python36\lib\site-packages\pony\utils\utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "c:\Python36\lib\site-packages\pony\orm\core.py", line 882, in generate_mapping
    if create_tables: database.create_tables(check_tables)
  File "<string>", line 2, in create_tables
  File "c:\Python36\lib\site-packages\pony\utils\utils.py", line 58, in cut_traceback
    return func(*args, **kwargs)
  File "<string>", line 2, in create_tables
  File "c:\Python36\lib\site-packages\pony\orm\core.py", line 413, in new_func
    try: return func(*args, **kwargs)
  File "c:\Python36\lib\site-packages\pony\orm\core.py", line 941, in create_tables
    if check_tables: database.schema.check_tables(database.provider, connection)
  File "c:\Python36\lib\site-packages\pony\orm\dbschema.py", line 77, in check_tables
    provider.execute(cursor, sql)
  File "<string>", line 2, in execute
  File "c:\Python36\lib\site-packages\pony\orm\dbapiprovider.py", line 53, in wrap_dbapi_exceptions
    except dbapi_module.OperationalError as e: raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: no such column: Announced.torrent`

**Comment by aroundmyroom** [comment]
looks like error in the database, with (one of the)  latest update you have to remove the brain.db
than it will be recreated

**Comment by aroundmyroom** [comment]
also make sure you run the requirements.txt again it has also an update in it.

**Comment by TRaSH-** [comment]
I'll try that when I get home,
Thnx.

**Comment by l3uddz** [comment]
Yeah sorry, should have made it clearer somehow. One of last updates has made change to SQLite database so required to remove it and it will be recreated. There are also more requirements like aroundmyroom mentioned so reinstall requirements.txt to install the missing ones. I'll try to make a windows install video when I have some more free time.

**Comment by TRaSH-** [comment]
Thnx that worked,
Not sure why the database got corrupted because it still worked with the older version.
But it works and that counts

**Comment by l3uddz** [comment]
Database wasn't corrupted, I made changes to it since you first installed. In future versions will have an upgrade database mechanism, but I don't think there will be many, if any more changes to the database structure.
